[package]
name = "ripbk-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.0"
chrono = "0.4.23"
dirs = "4.0.0"
image = "0.24.5"
percent-encoding = "2.2.0"
regex = "1.7.1"